-- Paintball Maps
-- Auto-generated by Envy Paintball

return {
    {
        id = "map_5155512_5474",
        name = "envy_test",
        center = vector3(165.11, -866.24, 29.87),
        radius = 13.00,
        spawns = {
            {x = 162.96, y = -859.71, z = 29.97, w = 93.13},
            {x = 170.59, y = -862.50, z = 29.76, w = 121.32},
        }
    }
}
