-- Paintball Maps
-- Auto-generated by Envy Paintball

return {
    {
        id = "map_1763414084_5420",
        name = "FFATest",
        center = vector3(191.64, -858.50, 30.55),
        radius = 50.00,
        spawns = {
            {x = 190.33, y = -854.06, z = 30.44, w = -20.41},
            {x = 196.81, y = -860.42, z = 30.38, w = -73.84},
        }
    },
    {
        id = "map_2580820_5085",
        name = "TeamTest",
        center = vector3(191.18, -858.62, 30.57),
        radius = 7.00,
        spawns = {
            {x = 182.98, y = -852.32, z = 30.26, w = 0.89, team = 1},
            {x = 200.34, y = -851.88, z = 29.98, w = -67.89, team = 1},
            {x = 197.74, y = -867.45, z = 30.60, w = -120.29, team = 2},
            {x = 182.15, y = -867.48, z = 30.28, w = 173.84, team = 2},
        }
    },
    {
        id = "map_1913717_8462",
        name = "gwapo",
        center = vector3(167.05, -861.09, 29.94),
        radius = 24.00,
        spawns = {
            {x = 162.73, y = -857.85, z = 29.99, w = 107.57},
            {x = 165.17, y = -853.39, z = 29.98, w = 79.97, team = 1},
            {x = 170.09, y = -853.86, z = 30.02, w = 71.71, team = 2},
        }
    }
}
