-- Paintball Weapons Configuration
-- Auto-generated by Envy Paintball
-- Categories are defined in config.lua

return {
    weapons = {
        { hash = -1063057011, name = "Special Carbine", category = "rifles", enabled = true },
        { hash = 584646201, name = "AP Pistol", category = "pistols", enabled = true },
        { hash = 2024373456, name = "SMG Mk2", category = "smgs", enabled = true },
        { hash = -1357824103, name = "Advanced Rifle", category = "rifles", enabled = true },
        { hash = -608341376, name = "Combat MG MK2", category = "rifles", enabled = true },
        { hash = 889558306, name = "Animated BASP", category = "smgs", enabled = true }
    }
}
