-- Paintball Weapons Configuration
-- Auto-generated by Envy Paintball
-- Categories are defined in config.lua

return {
    weapons = {
        { hash = 49308671, name = "GREENT", category = "rifles", enabled = true },
        { hash = -901401918, name = "SPYDER", category = "rifles", enabled = true },
        { hash = 584646201, name = "AP Pistol", category = "pistols", enabled = true }
    }
}
